# Generated by Django 4.2.7 on 2023-11-24 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_post_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(blank=True, choices=[('r1', 'Роман'), ('p', 'Поэма'), ('s', 'Стихотворение')], default='r1', max_length=2),
        ),
    ]
