# Generated by Django 4.2.7 on 2023-11-24 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Galaxy',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('age', models.FloatField(default=0, verbose_name='Возраст')),
                ('size', models.FloatField(default=0, verbose_name='Размер')),
            ],
            options={
                'verbose_name': 'Галактика',
                'verbose_name_plural': 'Галактики',
            },
        ),
        migrations.CreateModel(
            name='GalaxyType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, verbose_name='Тип галактики')),
            ],
            options={
                'verbose_name': 'Тип галактики',
                'verbose_name_plural': 'Типы галактики',
            },
        ),
        migrations.CreateModel(
            name='StarSystem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('age', models.FloatField(default=0, verbose_name='Возраст')),
                ('radius', models.FloatField(default=0, verbose_name='Радиус')),
                ('galaxy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='space.galaxy', verbose_name='Галактика')),
            ],
            options={
                'verbose_name': 'Звездная система',
                'verbose_name_plural': 'Звездные системы',
            },
        ),
        migrations.CreateModel(
            name='Star',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('age', models.FloatField(default=0, verbose_name='Возраст')),
                ('radius', models.FloatField(default=0, verbose_name='Радиус')),
                ('mass', models.FloatField(default=0, verbose_name='Масса')),
                ('temperature', models.FloatField(default=0, verbose_name='Температура')),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='space.starsystem', verbose_name='Звездная система')),
            ],
            options={
                'verbose_name': 'Звезда',
                'verbose_name_plural': 'Звезды',
            },
        ),
        migrations.CreateModel(
            name='Planet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('age', models.FloatField(default=0, verbose_name='Возраст')),
                ('radius', models.FloatField(default=0, verbose_name='Радиус')),
                ('mass', models.FloatField(default=0, verbose_name='Масса')),
                ('habitable', models.BooleanField(choices=[(False, 'жизни нет'), (True, 'возможна жизнь')], default=False, verbose_name='Обитаема ли')),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='space.starsystem', verbose_name='Звездная система')),
            ],
            options={
                'verbose_name': 'Планета',
                'verbose_name_plural': 'Планеты',
            },
        ),
        migrations.AddField(
            model_name='galaxy',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='space.galaxytype', verbose_name='Тип'),
        ),
    ]
